### ISSUE TITLE
possible file missing

### ISSUE THREAD

**Issue by ppcavalcante** [SoftwareSecurityLab/UbSym#1]
Hi!

I'm getting this error when trying to run benchmarks_running.py. Is this file missing, or maybe my setup is incomplete?

MCSimulation.py", line 24, in __init__
    with open(config_file,'r+') as handler:
FileNotFoundError: [Errno 2] No such file or directory: 'NFACTOR_MC.cfg'

**Comment by SaraBaradaran** [comment]
Hi,

Thank you for your comment! 
It was because of a file missing. I fixed it. Now you can run it.

**Comment by ppcavalcante** [comment]
Thank you very very much!
